language: node_js
node_js:
  - "18"
  - "20"
install:
  - npm install
before_script:
  - mocha --version
  - sleep 3 # give mocha some time to execute.
after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R dot && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
