name: Paperpress CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js \${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: \${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Mocha Version
      run: mocha --version
    - name: Sleep for 3 seconds
      run: sleep 3
    - name: Run tests and coverage
      run: |
        NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R dot
        cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
        rm -rf ./coverage
